-- :fennel:1747393478
vim.keymap.set({"n"}, "<esc>", "<esc><cmd>noh<cr>", {desc = "No highlight escape", silent = true})
vim.keymap.set({"n"}, "<leader>wx", "<C-w>x", {desc = "Swap windows", silent = true})
vim.keymap.set({"n"}, "<leader>ws", "<cmd>split<CR>", {desc = "split window horizontally", silent = true})
vim.keymap.set({"n"}, "<leader>wv", "<cmd>vsplit<CR>", {desc = "split window vertically", silent = true})
vim.keymap.set({"n"}, "<leader>wh", "<C-w>h", {desc = "focus window left", silent = true})
vim.keymap.set({"n"}, "<leader>wj", "<C-w>j", {desc = "focus window below", silent = true})
vim.keymap.set({"n"}, "<leader>wk", "<C-w>k", {desc = "focus window above", silent = true})
vim.keymap.set({"n"}, "<leader>wl", "<C-w>l", {desc = "focus window right", silent = true})
vim.keymap.set({"n"}, "<leader>b[", "<cmd>bprevious<CR>", {desc = "Previous buffer", silent = true})
vim.keymap.set({"n"}, "<leader>bl", "<cmd>e#<CR>", {desc = "Switch to last buffer", silent = true})
vim.keymap.set({"n"}, "<leader>bp", "<cmd>bprevious<CR>", {desc = "Previous buffer", silent = true})
vim.keymap.set({"n"}, "<leader>b]", "<cmd>bnext<CR>", {desc = "Next buffer", silent = true})
vim.keymap.set({"n"}, "<leader>bn", "<cmd>bnext<CR>", {desc = "Next buffer", silent = true})
vim.keymap.set({"n"}, "<leader>bd", "<cmd>q<CR>", {desc = "Kill buffer", silent = true})
vim.keymap.set({"n"}, "<leader><space>", "<cmd>FzfLua files<CR>", {desc = "TODO find project", silent = true})
vim.keymap.set({"n"}, "<leader>'", "<cmd>FzfLua resume<CR>", {desc = "Resume last search", silent = true})
vim.keymap.set({"n"}, "<leader>/", "<cmd>FzfLua live_grep<CR>", {desc = "Search project", silent = true})
vim.keymap.set({"n"}, "<leader><", "<cmd>FzfLua buffers<CR>", {desc = "Switch Buffer", silent = true})
vim.keymap.set({"n"}, "<leader>fD", "<cmd>bw<CR>", {desc = "Delete this file", silent = true})
vim.keymap.set({"n"}, "<leader>fs", "<cmd>w<CR>", {desc = "Save file", silent = true})
vim.keymap.set({"n"}, "<leader>fy", "<cmd>let @+ = expand('%')<CR>", {desc = "Yank replative path", silent = true})
vim.keymap.set({"n"}, "<leader>fY", "<cmd>let @+ = expand('%:p')<CR>", {desc = "Yank full path", silent = true})
vim.keymap.set({"n"}, "<leader>fC", "<cmd>%y+<CR>", {desc = "Copy file contents", silent = true})
vim.keymap.set({"n"}, "<leader>ff", "<cmd>FzfLua files<CR>", {desc = "Find file", silent = true})
vim.keymap.set({"n"}, "<leader>fr", "<cmd>FzfLua oldfiles<CR>", {desc = "Find recent file", silent = true})
vim.keymap.set({"n"}, "-", "<cmd>Oil<CR>", {desc = "Open file browser", silent = true})
vim.keymap.set({"n"}, "<leader>gg", "<cmd>Neogit<CR>", {desc = "Open Neogit", silent = true})
vim.keymap.set({"n"}, "<leader>gcc", "<cmd>Neogit<CR>", {desc = "Create commit", silent = true})
vim.keymap.set({"n"}, "<leader>sx", "<cmd>FzfLua commands<CR>", {desc = "M-x", silent = true})
vim.keymap.set({"n"}, "<leader>sh", "<cmd>FzfLua helptags<CR>", {desc = "Search help tags", silent = true})
vim.keymap.set({"n"}, "gr", "gd[{V%%::s/<CR>///gc<Left><Left><Left>", {desc = "Replace definition locally", silent = true})
return vim.keymap.set({"n"}, "gR", "gD:%%s/<CR>///gc<Left><Left><Left>", {desc = "Replace definition locally", silent = true})