-- :fennel:1749846265
local function _1_()
  vim.cmd.colorscheme("oxocarbon")
  vim.api.nvim_set_hl(0, "ErrorMsg", {fg = "#fa4d56"})
  vim.api.nvim_set_hl(0, "DiagnosticError", {fg = "#fa4d56"})
  vim.api.nvim_set_hl(0, "DiagnosticUnderlineError", {fg = "#fa4d56", undercurl = true})
  vim.api.nvim_set_hl(0, "Error", {fg = "#fa4d56", bg = "#262626"})
  vim.api.nvim_set_hl(0, "@error", {fg = "#fa4d56"})
  vim.api.nvim_set_hl(0, "HealthError", {fg = "#fa4d56"})
  vim.api.nvim_set_hl(0, "StatusLineDiagnosticError", {fg = "#fa4d56", bg = "#161616", bold = true})
  vim.api.nvim_set_hl(0, "NotifyERRORBorder", {fg = "#fa4d56"})
  vim.api.nvim_set_hl(0, "NotifyERRORIcon", {fg = "#fa4d56"})
  vim.api.nvim_set_hl(0, "NotifyERRORTitle", {fg = "#fa4d56"})
  vim.api.nvim_set_hl(0, "Removed", {fg = "#fa4d56"})
  vim.api.nvim_set_hl(0, "DiffRemoved", {fg = "#fa4d56"})
  vim.api.nvim_set_hl(0, "NeogitChangeDunstaged", {fg = "#fa4d56"})
  vim.api.nvim_set_hl(0, "NeogitChangeDeleted", {fg = "#fa4d56"})
  vim.api.nvim_set_hl(0, "NeogitChangeDuntracked", {fg = "#fa4d56"})
  vim.api.nvim_set_hl(0, "DiagnosticWarn", {fg = "#f1c21b"})
  vim.api.nvim_set_hl(0, "HealthWarning", {fg = "#f1c21b"})
  vim.api.nvim_set_hl(0, "StatusLineDiagnosticWarn", {fg = "#f1c21b", bg = "#161616", bold = true})
  vim.api.nvim_set_hl(0, "NotifyWARNBorder", {fg = "#f1c21b"})
  vim.api.nvim_set_hl(0, "NotifyWARNIcon", {fg = "#f1c21b"})
  vim.api.nvim_set_hl(0, "NotifyWARNTitle", {fg = "#f1c21b"})
  vim.api.nvim_set_hl(0, "DiagnosticOk", {fg = "#42be65"})
  vim.api.nvim_set_hl(0, "HealthSuccess", {fg = "#42be65"})
  vim.api.nvim_set_hl(0, "Added", {fg = "#42be65"})
  vim.api.nvim_set_hl(0, "DiffAdded", {fg = "#42be65"})
  vim.api.nvim_set_hl(0, "NeogitChangeModified", {fg = "#42be65"})
  vim.api.nvim_set_hl(0, "DiagnosticInfo", {fg = "#33b1ff"})
  vim.api.nvim_set_hl(0, "NotifyINFOBorder", {fg = "#33b1ff"})
  vim.api.nvim_set_hl(0, "NotifyINFOIcon", {fg = "#33b1ff"})
  vim.api.nvim_set_hl(0, "NotifyINFOTitle", {fg = "#33b1ff"})
  vim.api.nvim_set_hl(0, "Changed", {fg = "#33b1ff"})
  vim.api.nvim_set_hl(0, "WhichKeyIconGreen", {fg = "#3ddbd9"})
  vim.api.nvim_set_hl(0, "WhichKeyIconYellow", {fg = "#be95ff"})
  vim.api.nvim_set_hl(0, "WhichKeyIconOrange", {fg = "#be95ff"})
  vim.api.nvim_set_hl(0, "WhichKeyIconRed", {fg = "#ee5396"})
  vim.api.nvim_set_hl(0, "@org.headline.level1", {fg = "#ff7eb6", bold = true, underline = false})
  vim.api.nvim_set_hl(0, "@org.headline.level2", {fg = "#be95ff", bold = true, underline = false})
  vim.api.nvim_set_hl(0, "@org.headline.level3", {fg = "#78a9ff", bold = true, underline = false})
  vim.api.nvim_set_hl(0, "@org.headline.level4", {fg = "#3ddbd9", bold = true, underline = false})
  vim.api.nvim_set_hl(0, "@org.headline.level5", {fg = "#ffffff", bold = true, underline = false})
  vim.api.nvim_set_hl(0, "@org.headline.level6", {fg = "#33b1ff", bold = true, underline = false})
  vim.api.nvim_set_hl(0, "@org.headline.level7", {fg = "#08bdba", bold = true, underline = false})
  vim.api.nvim_set_hl(0, "@org.headline.level7", {fg = "#ee5396", bold = true, underline = false})
  vim.api.nvim_set_hl(0, "@org.priority.highest", {fg = "#fa4d56"})
  vim.api.nvim_set_hl(0, "@org.priority.default", {fg = "#fddc69"})
  vim.api.nvim_set_hl(0, "@org.priority.lowest", {fg = "#f2f2f2"})
  vim.api.nvim_set_hl(0, "@markup.list", {fg = "#78a9ff"})
  vim.api.nvim_set_hl(0, "OrgBulletsDash", {link = "@markup.list"})
  vim.api.nvim_set_hl(0, "@org.plan", {link = "Keyword"})
  return vim.api.nvim_set_hl(0, "@markup.link", {link = "markdownUrl"})
end
return {"nyoom-engineering/oxocarbon.nvim", config = _1_, lazy = false}